### ISSUE TITLE
师傅，下载链接失效了

### ISSUE THREAD

**Issue by s1g0day** [wyzxxz/fastjson_rce_tool#14]
打开download_url : https://toolaffix.oss-cn-beijing.aliyuncs.com/jndi_tool.zip 后直接返回oss报错界面

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<RequestId>61BACA8B99F00D313870123A</RequestId>
<HostId>toolaffix.oss-cn-beijing.aliyuncs.com</HostId>
<Key>jndi_tool.zip</Key>
</Error>`

**Comment by wyzxxz** [comment]
敏感时期，改下后缀下载，emlwIHRvIGphcg==

**Comment by s1g0day** [comment]
明白了，谢谢师傅
